
global:
  scrape_interval:     3s
  evaluation_interval: 10s

scrape_configs:
  - job_name: airflow
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['statsd-exporter:9102']
        labels:
          airflow_id: 'airflow'